=pod

=head1 NAME

 icewm-toolbar - icewm toolbar configuration file

=head1 SYNOPSIS

F<$HOME/.icewm/toolbar>

=head1 DESCRIPTION

=head1 FORMAT

=head1 EXAMPLES

=head1 FILES

=head1 SEE ALSO

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 LICENSE

B<IceWM> is licensed under the GNU Library General Public License.
See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
