=pod

=head1 NAME

 icewm-menu-fdo - menu generator for .desktop files

=head1 SYNOPSIS

B<icewm-menu-fdo> [I<FILENAME>]

=head1 DESCRIPTION

B<icewm-menu-fdo> introduces the XDG menu descriptors (aka
FreeDesktop.Org F<.desktop> files) to the menus of B<IceWM> window
manager.

=head1 ARGUMENTS

=over

=item [I<FILENAME>]

When provided with the optional I<FILENAME> argument that is the name
and location of a F<.desktop> file, B<icewm-menu-fdo> will open it and
launch the application using the C<Exec> line from the desktop file.

=back

=head1 OPTIONS

This program doesn't use command line options. In future, it might
support the pass-through of arguments to the command run from F<.desktop>
file's C<Exec> line.

=head1 USAGE

This utility is not normally used directly, but is used as the
executable in a B<menuprog> entry in a menu.

=head1 ENVIRONMENT

B<XDG_DATA_HOME> or B<XDG_DATA_DIRS> are considered as suggested by XDG Base Directory Specification.

=head1 CONFORMING TO

B<icewm-menu-fdo> complies roughly to the XDG F<.desktop> file and menu
specification, see L<Desktop Entry Specification>, Version 1.2alpha,
2015-03-06 and L<Desktop Menu Specification>, Version 1.1-draft, 31
March 2011.

=head1 CAVEATS

The B<icewm-menu-fdo> program is only built when the L<icewm(1)> package
is configured with the B<--enable-menus-fdo> option.

=head1 SEE ALSO

L<Desktop Entry Specification>,
L<Desktop Menu Specification>,
L<icewm(1)>,
L<icewm-preferences(5)>.

=head1 BUGS

B<icewm-menu-fdo> had no known bugs at the time of release.  Please report bugs
for current versions to the source code repository at
L<https://github.com/bbidulock/icewm/issues>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 LICENSE

B<IceWM> is licensed under the GNU Library General Public License.
See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
