=pod

=head1 NAME

 icewm-env - icewm environment configuration file

=head1 SYNOPSIS

=over

=item F<$ICEWM_PRIVCFG/env>

=item F<$XDG_CONFIG_HOME/icewm/env>

=item F<$HOME/.icewm/env>

=item F</etc/icewm/env>

=item F</usr/share/icewm/env>

=back

=head1 DESCRIPTION

L<icewm-session(1)> loads additional environment variables from the file
F<env>.

=head1 FORMAT

Each line is subjected to POSIX shell expansion by L<wordexp(3)>.
Comment lines starting by a hash-sign (C<#>) are ignored.
L<icewm-session(1)> will load those expanded lines which contain a name,
followed by an equals sign, followed by the value (which may be empty).

=head1 EXAMPLES

 # This is a comment.
 # And another.

 XDG_CURRENT_DESKTOP="ICEWM"
 XDG_MENU_PREFIX="unexicon-"

=head1 FILES

Locations for the toolbar options file are as follows:

=over

=item F<$ICEWM_PRIVCFG/env>

=item F<$XDG_CONFIG_HOME/icewm/env>

=item F<$HOME/.icewm/env>

=item F</etc/icewm/env>

=item F</usr/share/icewm/env>

=back

=head1 SEE ALSO

L<icewm(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 LICENSE

B<IceWM> is licensed under the GNU Library General Public License.
See the F<COPYING> file in the distribution.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
