=pod

=head1 NAME

 icewm-focus_mode - icewm focus mode configuration file

=head1 SYNOPSIS

=over

=item F<$ICEWM_PRIVCFG/focus_mode>

=item F<$XDG_CONFIG_HOME/icewm/focus_mode>

=item F<$HOME/.icewm/focus_mode>

=item F</etc/icewm/focus_mode>

=item F</usr/share/icewm/focus_mode>

=back

=head1 DESCRIPTION

Defines the initial value for C<FocusMode>.  Its default value is
C<FocusMode=1> (Click-to-focus).  This can be changed via the menu.
B<icewm> will save the Focus menu choice in this file.

=head1 FORMAT

The file contains a single line containing the preferences assignment
for B<FocusMode>.

=head1 EXAMPLES

The following is my F<focus_mode> file:

 FocusMode=2

=head1 FILES

Locations for the toolbar options file are as follows:

=over

=item F<$ICEWM_PRIVCFG/focus_mode>

=item F<$XDG_CONFIG_HOME/icewm/focus_mode>

=item F<$HOME/.icewm/focus_mode>

=item F</usr/share/icewm/focus_mode>

=item F</usr/local/share/icewm/focus_mode>

=back

=head1 SEE ALSO

L<icewm(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

=head1 LICENSE

B<IceWM> is licensed under the GNU Library General Public License.
See the F<COPYING> file in the distribution.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
