#!/bin/sh

for arg
do
    case $arg in
        -h|-?|--help|--?)
            echo "Usage: $0"
            echo "Set the Gnome windowmanager to IceWM"
            exit 0
            ;;
        -V|--version)
            echo "$0 VERSION, Copyrighted."
            exit 0
            ;;
        *)
            : echo "$0: Ignoring argument '$arg'." >&2
            ;;
    esac
done

echo Previous window manager:
gconftool-2 -g /desktop/gnome/session/required_components/windowmanager


gconftool-2 -s /desktop/gnome/session/required_components/windowmanager --type string icewm

echo New window manager:
gconftool-2 -g /desktop/gnome/session/required_components/windowmanager
