/* XPM */
static char *vim[] = {
/* columns rows colors chars-per-pixel */
"48 48 8 1",
"# c Gray0",
"a c #000080",
"b c #008000",
"c c Green",
"d c #808080",
"e c #c0c0c0",
"f c Gray100",
". c None",
/* pixels */
".......................###......................",
"......................#ccc#.....................",
".....................#cbbbc#....................",
".....################cbbbbbc#.##############....",
"....#ffffffffffffffff#bbbbbbc#ffffffffffffff#...",
"....#fffffffffffffffff#bbbbbb#fffffffffffffff#..",
"....#feeeeeeeeeeeeeeedd#bbbbb#ffeeeeeeeeeeeedd#.",
".....#eeeeeeeeeeeeeeedd#bbbbbb##eeeeeeeeeeeedd#.",
".....#eeeeeeeeeeeeeeedd#bbbbbbbb#deeeeeeeeeedd#.",
"......##deeeeeeeeeddd##bbbbbbbbb#deeeeeeeeeddd#.",
".......#feeeeeeeeedd#bbbbbbbbbb#feeeeeeeeeddd#..",
".......#feeeeeeeeedd#bbbbbbbbb#ffeeeeeeeeddd#...",
".......#feeeeeeeeedd#bbbbbbbb#ffeeeeeeeeddd#....",
".......#feeeeeeeeedd#bbbbbbb#ffeeeeeeeeddd#.....",
".......#feeeeeeeeedd#bbbbbb#ffeeeeeeeeddd#......",
".......#feeeeeeeeedd#bbbbb#ffeeeeeeeeddd#.......",
".......#feeeeeeeeedd#bbbb#ffeeeeeeeeddd##.......",
"......##feeeeeeeeedd#bbb#ffeeeeeeeeddd#aa#......",
".....#c#feeeeeeeeedd#bb#ffeeeeeeeeddd#bbba#.....",
"....#cb#feeeeeeeeedd#b#ffeeeeeeeeddd#bbbbba#....",
"...#cbb#feeeeeeeeedd##ffeeeeeeeeddd#bbbbbbba#...",
"..#cbbb#feeeeeeeeedd#ffeeeeeeeeddd#bbbbbbbbba#..",
".#cbbbb#feeeeeeeeeddffeeeeeeeeddd#bbbbbbbbbbba#.",
"#cbbbbb#feeeeeeeeeddfeeeeeeeeddd#bbbbbbbbbbbbba#",
".#cbbbb#feeeeeeeeeddeeeeeeeeddd#bbbbbbbbbbbbbba#",
"..#cbbb#feeeeeeeeeeeeeeeeeeddd#bbbbbbbbbbbbbb##.",
"...#cbb#feeeeeeeeeeeeeeeeeddd#bbbbbbbbbbbbbba#..",
"....#cb#feeeeeeeeeeeeeee#####bbbbbbbbbbbbbba#...",
".....#c#feeeeeeeeeeeeee#eee#bbbbbbbbbbbbbba#....",
"......##feeeeeeeeeeeeee#eee#bbbbbbbbbbbbba#.....",
".......#feeeeeeeeeeeeee#eee#bbbbbbbbbbbba#......",
".......#feeeeeeeeeeeeed####bbbbbbbbbbbba#.......",
".......#feeeeeeeeeeeedd####bb####bb####a####....",
".......#feeeeeeeeeeedddeeee##eeee##eeee##eee#...",
".......#feeeeeeeeeeddd##eee#b#eeeeeeeeeeeeeee#..",
".......#feeeeeeeeeddd#b#eee#b#eeeeeeeeeeeeeee#..",
".......#feeeeeeeeddd#b#eee#bb#eee###eee###ee#...",
".......#feeeeeeeddd#bb#eee#b#eeee##eeee##eee#...",
".......#feeeeeeddd#bb#eee#bb#eee#a#eee##eee#....",
".......#feeeeeddd#bbb#eee#b#eee#a#eee#.#eee#....",
".......#feeeeddd##bb#eee#bb#eee#.#eee##eee#.....",
".......#feeeddd#.#bb#eee#b#eee#a#eee#.#eee#.....",
"........#eeddd#...###eeee##eeee##eeee##eeee#....",
".........#####.....######ba####..####..#####....",
"....................#bbbbaa#....................",
".....................#aaaa#.....................",
"......................#aa#......................",
".......................##......................."
};
