ICESOUND(1)
==========
:doctype: manpage


NAME
----
icesound - play audio files when interesting GUI events happen


SYNOPSIS
--------
*icesound* ['OPTIONS']


DESCRIPTION
-----------
The IceWM window manager can be configured to generate
so-called GUI events in response to interesting actions,
like opening or closing of application windows,
switching of workspace, etc.
GUI events are a property of the root window.
IceWM changes this property when a new GUI event occurs.
Interested applications can listen for changes to this property.
GUI events are an optional feature of IceWM.
It must be explicitly enabled by giving the
`--enable-guievents` option during configuration.
There are nearly twenty GUI events defined.
The `--list-sounds` option will show them.

Icesound is an application, which is part of the IceWM
suite of applications, which responds to these GUI events
by playing audio files. These sound files are '.WAV' files
located in a `sounds` subdirectory in one of the IceWM
configuration directories.

Icesound supports several common audio interfaces.
These are: ALSA, ESounD, OSS and libAO.
These must be enabled during configuration.
ALSA, OSS and libAO all require support for 'libsndfile',
which is a very common library to read audio files.

'ALSA' is rather involved to program and it works,
but this could use more testing.
It plays at most one sound at a time.

The 'ESounD' interface is much simpler to implement
and this works very well, because the difficult
details are handled by the 'ESounD Sound Daemon'.
It supports mixing of sounds when multiple GUI
events occur within a second.
This may be the best option currently.
It requires that `esd` is running and
that icesound can connect to it.

'LibAO' is a cross-platform audio output library
which is a convenient wrapper around a
significant number of common audio interfaces.
It has a simple configuration file
which is documented in the libao.conf(5) manpage.

The 'Open Sound System (OSS)' is a cross-platform
sound interface, which is fully supported by icesound.

When multiple audio interfaces are available
icesound will examine them all until it finds
one which it can connect to and then use that one.
By default it prefers them in the order of:
`AO,ESD,ALSA,OSS`.


OPTIONS
-------
*-d, --display=DISPLAY*::
  X11 display used by IceWM (default: $DISPLAY).

*-s, --sample-dir=DIR*::
  Specifies a directory with sound files.
  The default is:
  `$HOME/.config/icewm/sounds`,
  `$HOME/.icewm/sounds`,
  `CFGDIR/sounds`
  and `LIBDIR/sounds`.
  See the output of
  `icewm --directories`.

*-i, --interface=LIST*::
  Specifies the audio output interfaces. One or more of: +
  `AO,ESD,ALSA,OSS` separated by commas.

*-D, --device=DEVICE*::
  Backwards compatibility only: the default device. +
  Please prefer one of the `-A/-O/-S` options.

*-O, --oss=DEVICE*::
  Specifies the OSS device (default: `default`).

*-A, --alsa=DEVICE*::
  Specifies the ALSA device (default: `/dev/dsp`).

*-S, --server=ADDR:PORT*::
  Specifies the ESD server address and port number. +
  For ESD the default is `localhost:16001`.

*-z, --snooze=milliseconds*::
  Specifies the snooze interval between sound events +
  in milliseconds. Default is 500 milliseconds.

*-p, --play=sound*::
  Plays the given sound (name or number) and exits.

*-l, --list-files*::
  Lists the available sound file paths and exits.

*--list-sounds*::
  Lists the supported sound filenames and exits.

*--list-interfaces*::
  Lists the supported audio interfaces and exits.

*-v, --verbose*::
  Be verbose and print some information when sound events occur.

*-V, --version*::
  Prints version information and exits.

*-h, --help*::
  Prints this help screen and exits.


RETURN VALUES
-------------

  0    Success.
  1    General error.
  2    Command line error.
  3    Subsystems error (ie cannot connect to server).


BUGS
----
You are welcome to give your feedback about icesound on +
https://github.com/bbidulock/icewm/issues.


RESOURCES
---------
Github: https://github.com/bbidulock/icewm

Example sound files: http://triq.net/theme/icefx


SEE ALSO
--------
icewm(1),
libao.conf(5),
esd(1),
padsp(1),
aplay(1),
alsamixer(1).


COPYING
-------
Icesound is licensed under the GNU Library General Public License.
See the file COPYING in the distribution for full details.

