.ds AK \s-1IceWM\s+1
.ds EP \fIIceWM: Window Manager\fP
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.TH ICEWM 1 "2017-06-06" "Adam Pribyl" "IceWM Window Manager"

.SH NAME
icewm \- lightweight X11 window manager

.SH SYNOPSIS
.B icewm-session [options...]

.SH DESCRIPTION
.I IceWM
is a lightweight X11 window manager.
It aims to be a small, fast and familiar window
manager for the X11 window system. Compatibility with the
ICCCM 2.0 and EWMH window manager protocols is an important goal.

IceWM was originally designed to emulate the look of Motif, OS/2 Warp
4, OS/2 Warp 3 and Windows 95. Since it has a theming engine (hint:
http://www.icewm.org/) other styles are possible.
The installation comes with several preconfigured themes.
The IceWM menu allows to choose between them.

Generally, it tries to make all functions available
by both keyboard and mouse.
Configurability is very good through various preferences files.

IceWM consists of several programs:

.B icewm
- the actual window manager. It positions application windows
on screen and decorates them with borders. It gives input focus to
the current active application. Icewm supports three different
focus modes: click to focus, sloppy mouse focuse and a custom
user-definable focus mode. Icewm also draws a small taskbar
at the bottom of the screen, which gives easy access to programs,
to active applications, and to a small set of monitoring applets.

.B icewmbg
- the background setting application. It can assign plain
background color or images in different formats to the X background,
shared or separated for different workspaces. This program should be
started before
.I icewm
.

.B icewmtray
- catches the Docklet objects installed by various
applications like PSI.

.B icewm-session
- runs all of the above when needed.
It implements basic session management.
This is the preferred program to start the IceWM system.

.B icesh
- could be used to manage IceWM internals from command line.

.B icewmhint
- used internally.

.B icesound
- plays audio files on GUI events raised by IceWM.

.B icewm-menu-fdo
- generate an IceWM menu with executable desktop applications
according to Freedesktop.org specifications.

.SH OPTIONS
.TP
Each of the IceWM executables supports the following options:
.TP
.B \-c, \-\^\-config=FILE
Use FILE as the source of configuration options.
By default IceWM looks for a file named "preferences".
Typically this file is stored as one of ~/.config/icewm/preferences,
or ~/.icewm/preferences, or in one of the configuration
directories explained below. It contains a long list of options
which allow the user to tweak the behavior of IceWM to ones taste.
A default
.I preferences
file contains comments about the purpose
of each option, the range of useful values and the
current or default value. A preferences file is a readable
text file which can be modified with the help of a text editor.
If this option is given to icewm-session then it is passed
on to icewm. If icewm is started independently then this option
can be given to icewm directly. However, usually one will
want to use a preferences file from a default location.

.TP
.B \-t, \-\^\-theme=FILE
Use FILE as the name of the IceWM
.I theme
to use.
A theme defines the look and feel of IceWM,
like colors, fonts, buttons and button behavior.
Originally a theme defined options to emulate
the appearance of other desktop environments,
like Motif, OS/2 Warp, or Windows.
Over the years many new original themes have been
designed with beautiful icons and backgrounds, which
advance the state of the art in desktop look and feel.
Many of them can be downloaded from the website
https://www.box-look.org/ and stored in either the
directory ~/.config/icewm/themes/ or in ~/.icewm/themes/.
The user can then activate such a theme via the
IceWM menu in the lower left corner of the display.
A default theme is usually specified in either
~/.icewm/theme, or in ~/.config/icewm/theme.
When a new theme is selected then this value is overwritten,
so that the next time IceWM is started this choice is reused.

.TP
.B \-\^\-display=NAME
NAME specifies the connection to the X11 server.
If this option is missing, as is usually the case,
then NAME is read from the environment variable DISPLAY.
Its default value is typically just :0.

.TP
.B \-\^\-sync
This option is sometimes used in software development of IceWM.
It specifies to use a slower synchronous communication mode
with the X11 server.  This is irrelevant for normal use of IceWM.

.TP
.B \-h, \-\^\-help
Gives a complete list of all the available command line options
with some very brief explanation.

.TP
.B \-V, \-\^\-version
Shows the software release version for this program.

.TP
The icewm program supports some additional options:

.TP
.B --replace
Instructs IceWM to replace an existing window manager.
Once that window manager notices that it is to be replaced
it will cease operations and typically stop execution.
This allows IceWM to establish itself as the only active
window manager.

.TP
.B --restart
Instructs IceWM to restart itself, but one should not
use this option directly. Instead one selects the
.B Restart Icewm
button from the menu in the lower left corner of the desktop.

.TP
.B --configured
Shows a list of configuration options which were
enabled when IceWM was compiled from source code.
This can be helpful if one suspects some functionality may be missing.

.TP
.B --directories
Gives a list of directories where IceWM will look for configuration data.
This list is printed in the actual order in which IceWM uses it
to search for configuration files.

.TP
.B --list-themes
Icewm will search all the configuration directories for
theme files and print a list of all found themes.

.TP
.B --postpreferences
This gives a long list of all the internal IceWM options
with their actual values after icewm has processed all of
the configuration and theme files. In some advanced
scenarios this can be helpful to inspect which configuration
was chosen or whether option formatting was correct.


.PD 1
.SH ENVIRONMENT VARIABLES

.I XDG_CONFIG_HOME=PATH
.RS
The directory for user private configuration files.
The default value is "$HOME/.config/icewm/".
.RE

.I ICEWM_PRIVCFG=PATH
.RS
The directory for user private configuration files.
The default value is "$HOME/.icewm/".
.RE

.I DISPLAY=NAME
.RS
The name of the X11 server.
See Xorg(1) or Xserver(1).
This value can be overridden by the --display option.
.RE

.I MAIL=URL
.RS
Location of your mailbox. If the schema is omitted the local "file"
schema is assumed. This is used by the mailbox applet.
.RE

.SH FILES
IceWM looks for configuration files in the following directories,
in the given order, until it finds one:

.I $HOME/.config/icewm/
.RS
Contains user-specific configurations.
.RE

.I $HOME/.icewm/
.RS
Contains user-specific configurations.
.RE

.I /etc/icewm/
or
.I /etc/X11/icewm/
.RS
Contains system-wide customized defaults.
Please note that your local installation may have been
configured to use a different system location.
The icewm --directories option will show this location.
.RE

.I /usr/share/icewm/
or
.I /usr/local/share/icewm/
.RS
Default local installation settings.
.RE

.B Configuration files

.I keys
.RS
Global keybindings to launch applications,
which need not be window manager related.
Each non-empty line starts with the word
.B key.
After one or more spaces follows a double-quoted string
of the bound X11 key combination like "Alt+Ctrl+Shift+X".
Then after at least one space follows a shell command line which
will be executed by IceWM whenever this key combination is pressed.
.RE

.I menu
.RS
A menu of startable applications; usually customized by the user.
IceWM provides either the program
.I icewm-menu-fdo
or the program
.I icewm-menu-gnome2
to generate a default menu.
.RE

.I preferences
.RS
Contains general settings like paths, colors and fonts,
but also options to control the IceWM focus behavior
and the applets which are started in the taskbar.
The icewm installation will provide a default
.I preferences
file, which can be copied to the IceWM user
configuration directory and modified.
.RE

.I prefoverride
.RS
Settings which override the settings from a theme.
Some of the IceWM configuration options from the
preferences file which control the look-and-feel
may be overridden by the theme,
if the theme designer thinks this is desirable.
However, this
.I prefoverride
file will again override this for a
few specific options of your choosing.
It is safe to leave this file empty initially.
.RE

.I programs
.RS
An automatically generated menu of startable applications.
This could be used by wmconfig, menu or similar programs
to give easy access to all the desktop applications
which are installed on the system.
.RE

.I theme
.RS
This file contains the name of the default theme.
On startup icewm reads this file to obtain the theme name,
unless icewm was started with the --theme option.
Whenever a different theme is selected from the IceWM Menu then
the theme file is overwritten with the name of the selected theme.
This theme file contains the keyword
.B Theme,
followed by an equals sign,
followed by a double-quoted string with the theme name.
The theme name is the name of the theme directory,
followed by a slash, followed by the theme file.
Usually the theme file is just "default.theme",
but a theme may have alternatives.
Alternatives are small tweakings of a theme.
These are specified in their own ".theme" file,
which replaces "default.theme".
If no theme file exists then IceWM will use the
default setting of Theme="default/default.theme".
.RE

.I toolbar
.RS
Contains names of quick to launch applications with icons for the taskbar.
Each non-empty non-comment line starts with the keyword
.B prog.
After one or more spaces follows a name, which is displayed in a
tooltip whenever the mouse cursor hovers over the toolbar icon.
This name may be a double quoted string.
Then follows the bare name of the icon to use without extensions.
This icon will be shown in the toolbar.
The last component is a shell command line which will be executed
whenever the user presses the icon in the toolbar.
.RE

.I winoptions
.RS
Contains settings to control window appearance and behavior
which are specific to applications or groups of applications.
Options can control the border, whether it appears on the
taskbar, the window list, the system tray and the workspaces.
Also its layer, geometry, whether it is movable, resizable
and closable.
Full details for this file are explained in the
.I IceWM Manual
.
.RE

.I startup
.RS
Commands to execute on IceWM startup.
This is an executable script with commands to tweak
X11 settings and launch some applications which need
to be active whenever IceWM is started.
.RE

.I shutdown
.RS
Commands to execute on IceWM shutdown.
This is an executable script with commands to be
executed in the last stage of IceWM termination.
Typically they may undo some of the effects of the
.I startup
script.
.RE

.B Configuration directories

.I icons
.RS
Contains icons which are used to picturally identify applications.
Usually these files are in the XPM format,
but the PNG and SVG image formats are also supported.
The names of icon files may follow a specific naming pattern, like
.I app_32x32.xpm
.
They start with a basename, usually this is just a single word.
Then follows an underscore, followed by a size specification in
the format _SIZExSIZE.
This is followed by a dot and the file extension,
where the extension denotes the icon image format.
Common sizes are 16, 32 and 48 for small, large and huge icons.
This depends on the respective IconSize preferences options.
.RE

.I ledclock
.RS
Pictures of digits for the LED clock which is displayed in
the bottom-right corner of the taskbar.
These can be seen when the TaskBarShowClock and TaskBarClockLeds
options are both set to 1.
.RE

.I mailbox
.RS
Icons which are used to display different states of
the mailbox applet in the taskbar.
There are five states and each has its own icon:
mail.xpm, newmail.xpm, unreadmail.xpm, nomail.xpm, errmail.xpm.
.RE

.I taskbar
.RS
Pictures to customize the look of the taskbar.
These include:
taskbarbg.xpm,
taskbuttonactive.xpm,
taskbuttonbg.xpm,
taskbuttonminimized.xpm,
toolbuttonbg.xpm,
workspacebuttonactive.xpm,
workspacebuttonbg.xpm.
.RE

.I themes
.RS
A directory to store themes.
Each theme is stored in its own subdirectory in the
.I themes
directory. A theme contains at least a
.I default.theme
file, and optionally
.I "theme alternatives"
which are additional files which have a ".theme"
filename extension and which contain tweakings
of the "default.theme" file.
.RE

.SH EXAMPLES
Examples of the above configuration files
can be found in the default installation
path or in the system-wide defaults.
See the output of
.I icewm --directories
for their locations.

.SH CONFORMING TO
ICCCM 2.0: mostly.  EWMH: mostly.
See the file COMPLIANCE in the distribution for full details.

.SH SEE ALSO
.IR xinit(1),
.IR Xorg(1),
.IR X(7),

.IR "IceWM Help"
from the IceWM menu contains a manual (somewhat outdated, but still useful).

.IR http://www.icewm.org/manual/
gives the IceWM Manual (somewhat outdated).

.IR http://www.icewm.org/FAQ/
gives frequently asked questions.

.IR http://www.icewm.org/themes/
explains how to design new themes.

.IR https://github.com/bbidulock/icewm/
for current software development.

.IR https://www.box-look.org/browse/cat/142/ord/latest/
for new themes.

.SH BUG REPORTS
If you find a bug in IceWM
please use the bug reporting system on
.BR https://github.com/bbidulock/icewm/issues
to report it. We welcome all friendly feedback.

.SH COPYING
IceWM is licensed under the GNU Library General Public License.
See the file COPYING in the distribution for full details.
