.ds AK \s-1IceWM\s+1
.ds EP \fIIceWM: Window Manager\fP
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.TH ICEWM 1 "2017-06-05" "Adam Pribyl" "Window Manager"

.SH NAME
icewm \- lightweight X11 window manager

.SH SYNOPSIS
.B icewm-session [options...]

.SH DESCRIPTION
.I IceWM
is a lightweight X11 window manager.
It aims to provide a small, fast and familiar window
manager for the X11 window system. Compatibility with the
ICCCM 2.0 and EWMH window manager protocols is an important goal.

IceWM was originally designed to emulate the look of Motif, OS/2 Warp
4, OS/2 Warp 3 and Windows 95. Since it has a theming engine (hint:
http://www.icewm.org/) other styles are possible.
The installation comes with several preconfigured themes.
The IceWM menu allows to choose between them.

Generally, it tries to make all functions available
both by keyboard and by mouse.
Configurability is very good through various preferences files.

IceWM consists of several parts:

.B icewm 
- the actual window manager. It positions application windows
on screen and decorates them with borders. It gives input focus to
the current active application.

.B icewmbg 
- the background setting application. It can assign plain
background color or images in different formats to the X background,
shared or separated for different workspaces. This program should be
started before IceWM startup.

.B icewmtray 
- catches the Docklet objects installed by various
applications like PSI.

.B icewm-session 
- runs all of the above when needed.
It implements basic session management.
This is the preferred program to start the IceWM system.

.B icesh
- could be used to manage IceWM internals from command line.

.B icewmhint
- used internally.

.B icesound
- plays audio files on GUI events raised by IceWM.

.SH OPTIONS
.TP
Each of the IceWM executables supports the following options:
.TP
.B \-c, \-\^\-config=FILE
Use FILE as the source of configuration options.
By default IceWM looks for a file named "preferences".
Typically this file is stored as one of ~/.config/icewm/preferences,
or ~/.icewm/preferences, or in one of the configuration
directories explained below. It contains a long list of options
which allow the user to tweak the behavior of IceWM to ones taste.
A default preferences file contains comments about the purpose
of each option, the range of useful values and the
current or default value. A preferences file is a readable
text file which can be modified with the help of a text editor.
If this option is given to icewm-session then it is passed
on to icewm. If icewm is started independently then this option
can be given to icewm directly. However, usually one will
want to use a preferences file from a default location.

.TP
.B \-t, \-\^\-theme=FILE
Use FILE as the name of the IceWM
.I theme
to use.
A theme defines the look and feel of IceWM,
like colors, fonts, buttons and button behavior.
Originally a theme defined options to emulate
the appearance of other desktop environments,
like Motif, OS/2 Warp, or Windows.
Over the years many new original themes have been
designed with beautiful icons and backgrounds, which
advance the state of the art in desktop look and feel.
Many of them can be downloaded from the website
https://www.box-look.org/ and stored in either the
directory ~/.config/icewm/themes/ or in ~/.icewm/themes/.
The user can then activate such a theme via the
IceWM menu in the lower left corner of the display.
A default theme is usually specified in either
~/.icewm/theme, or in ~/.config/icewm/theme.
When a new theme is selected then this value is overwritten,
so that the next time IceWM is started this choice is reused.

.TP
.B \-\^\-display=NAME
NAME specifies the connection to the X11 server.
If this option is missing, as is usually the case,
then NAME is read from the environment variable DISPLAY.
Its default value is typically just :0.

.TP
.B \-\^\-sync
This option is sometimes used in software development of IceWM.
It specifies to use a slower synchronous communication mode
with the X11 server.  This is irrelevant for normal use of IceWM.

.TP
.B \-h, \-\^\-help
Gives a complete list of all the available command line options
with some very brief explanation.

.TP
.B \-V, \-\^\-version
Shows the software release version for this program.

.TP
The icewm program supports some additional options:

.TP
.B --replace
Instructs IceWM to replace an existing window manager.
Once that window manager notices that it is to be replaced
it will cease operations and typically stop execution.
This allows IceWM to establish itself as the only active
window manager.

.TP
.B --restart
Instructs IceWM to restart itself, but one should not
use this option directly. Instead one selects the 
.B Restart Icewm
button from the menu in the lower left corner of the desktop.

.TP
.B --configured
Shows a list of configuration options which were
enabled when IceWM was compiled from source code.
This can be helpful if one suspects some functionality may be missing.

.TP
.B --directories
Gives a list of directories where IceWM will look for configuration data.
This list is not in the actual order in which IceWM uses it.
However, for each directory one can inspect its contents
for configuration possibilities.

.TP
.B --postpreferences
This gives a long list of all the internal IceWM options
with their actual values after icewm has processed all of
the configuration and theme files. In some advanced
scenarios this can be helpful to inspect which configuration
was chosen or whether option formatting was correct.


.PD 1
.SH ENVIRONMENT VARIABLES

.I XDG_CONFIG_HOME=PATH
.RS
Directory to use for user private configuration files, "$HOME/.config/icewm/" 
by default.
.RE

.I ICEWM_PRIVCFG=PATH  
.RS
Directory to use for user private configuration files, "$HOME/.icewm/" 
by default.
.RE

.I DISPLAY=NAME
.RS
Name of the X server to use, depends on Xlib by default.
See Xorg(1) or Xserver(1).
.RE

.I MAIL=URL
.RS
Location of your mailbox. If the schema is omitted the local "file" 
schema is assumed.
.RE

.SH FILES
IceWM looks for its configuration files in the following directories, 
in the following order:

.I $HOME/.config/icewm/
.RS
User-specific configurations.
.RE

.I $HOME/.icewm/
.RS
User-specific configurations.
.RE

.I /etc/X11/icewm/
.RS
System-wide customized defaults.
.RE

.I /usr/local/share/icewm/
.RS
Default installation settings.
.RE

.B Configuration files

.I keys
.RS
Global keybindings to launch applications (not window manager related).
.RE

.I menu
.RS
A menu of startable applications; usually customized by the user.
.RE

.I preferences
.RS
Contains general settings - paths, colors, fonts...
.RE

.I prefoverride
.RS
Settings which override the settings from a theme.
.RE

.I programs
.RS
An automatically generated menu of startable applications 
(this should be used for wmconfig, menu or similar packages, 
perhaps as a part of the login or X startup sequence)
.RE

.I theme
.RS
The currently selected theme.
.RE

.I toolbar
.RS
Contains names of quick to launch applications with icons for the taskbar.
.RE

.I winoptions
.RS
Application window options.
.RE

.I startup
.RS
Commands to execute on IceWM startup.
.RE

.I shutdown
.RS
Commands to execute on IceWM shutdown.
.RE

.B Configuration directories

.I icons
.RS
Icons used for applications (usually XPM files *_16x16.xpm and *_32x32.xpm).
.RE

.I ledclock
.RS
Pictures of digits for the LED clock displayed in taskbar.
.RE

.I mailbox
.RS
Icons used for different states of the mailbox.
.RE

.I taskbar
.RS
Pictures to customize the look of the taskbar.
.RE

.I themes
.RS
Directory to store themes.
.RE

.SH EXAMPLES
Examples of the above configuration files
can be found in the default installation 
path or in the system-wide defaults.

.SH CONFORMING TO
ICCCM 2.0: mostly.  EWMH: mostly.
See the file COMPLIANCE in the distribution for full details.

.SH SEE ALSO
.IR xinit(1),
.IR Xorg(1),
.IR X(7),

.IR "IceWM Help"
from the IceWM menu contains a manual (currently outdated).

.IR http://www.icewm.org/manual/
gives an outdated manual.

.IR http://www.icewm.org/FAQ/
gives frequently asked questions.

.IR http://www.icewm.org/themes/
explains how to design new themes.

.IR https://github.com/bbidulock/icewm/
for current software development.

.IR https://www.box-look.org/browse/cat/142/ord/latest/
for new themes.

.SH BUG REPORTS
If you find a bug in IceWM
please use the bug reporting system on
.BR https://github.com/bbidulock/icewm/issues
to report it. We welcome all friendly feedback.

.SH AUTHORS
The original version of IceWM was designed
and implemented in 1997 by Marko Macek.
In the year 2001 it was maintained by Mathias Hasselmann.
Then again Marko Macek took over.

The original version of this manual page was written
in 2005 by Adam Pribyl, covex@ahoj.fsik.cvut.cz.

.SH COPYING
IceWM is licensed under the GNU Library General Public License.
See the file COPYING in the distribution for full details.
