#!/bin/sh

grep -n '".*"' src/*.cc |\
egrep -v '#(include|define.*(PIXMAP))|extern.*"C"|[^"]*(//|/\*|"(\.\.\.|%s,\*|rgb:../../..|/bin/(sh|rm)|-c|/dev/null|DISPLAY=?|/?)")|_\(|MSG|loadPixmap|getIcon|X(LoadQueryFont|CreateFontSet)|{ &_?XA|getenv|msg|/?(.icewm|themes|icons|mailbox|ledclock|taskbar|proc)/|"-|"([: ]*(0x|)%[0-9]*[%xsd][: ]*)*"'

grep -n '".*"' src/*.h |\
egrep -v '#(include|define.*(FONT|KEY_NAME|CONFIG_))extern.*"C"||[OX][BIKS]V|XA_(WIN|MOTIF)|ICEWM_GUI_EVENT|{ ge|defgKey|warn|"display"'
